apiVersion: apps/v1
kind: Deployment
metadata:
  name: argus
  labels:
    app: argus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argus
  template:
    metadata:
      labels:
        app: argus
    spec:
      containers:
      - name: argus
        image: argus:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ETHEREUM_RPC_URL
          value: "https://eth.llamarpc.com"
        - name: BASE_RPC_URL
          value: "https://base.llamarpc.com"
        - name: SERVER_PORT
          value: "8080"
        - name: CEX_PROVIDER
          value: "coinbase"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1001

---
apiVersion: v1
kind: Service
metadata:
  name: argus-service
  labels:
    app: argus
spec:
  selector:
    app: argus
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP